services:
  storage_service:
    build:
      context: ./storage_service
      dockerfile: Dockerfile
    container_name: storage_service
    restart: unless-stopped
    ports:
      - "${STORAGE_PORT}:${STORAGE_PORT}"
    volumes: 
      - ${STORAGE_DIR}:/shared_data
    environment:
      - STORAGE_PATH=/shared_data
      - DB_PATH=/shared_data/database.db
      - FLASK_DEBUG=${FLASK_DEBUG}
      - STORAGE_PORT=${STORAGE_PORT}
    networks:
      - ml_pipeline_net

  collector_service:
    build:
      context: ./collector_service
      dockerfile: Dockerfile
    container_name: collector_service
    restart: unless-stopped
    ports:
      - "${COLLECTOR_PORT}:8501"
    environment:
      - STORAGE_URL=http://storage_service:${STORAGE_PORT}
    depends_on:
      - storage_service
    networks:
      - ml_pipeline_net

  impute_service:
    build:
      context: ./impute_service
      dockerfile: Dockerfile
    container_name: impute_service
    restart: unless-stopped
    ports:
      - "${IMPUTE_PORT}:8501"
    environment:
      - STORAGE_URL=http://storage_service:${STORAGE_PORT}
      - ML_URL=http://ml_service:${ML_PORT}
    depends_on:
      - storage_service
    networks:
      - ml_pipeline_net

  visualization_service:
    build:
      context: ./visualization_service
      dockerfile: Dockerfile
    container_name: visualization_service
    restart: unless-stopped
    ports:
      - "${VISUALIZATION_PORT:-5005}:8501"
    environment:
      - WEB_MASTER_URL=http://web_master:${WEB_MASTER_PORT:-8000}
      - STORAGE_URL=http://storage_service:${STORAGE_PORT:-5001}
    depends_on:
      - storage_service
    networks:
      - ml_pipeline_net

networks:
  ml_pipeline_net:
    driver: bridge
      
